import { AppShell, Footer, Group, Header, Text } from "@mantine/core";
import MyFooter from "./MyFooter";
import Head from "next/head";
import Link from "next/link";

export const ApplicationContainer = ({ children }) => {
	return (
		<div className="text-[#123693]">
			<Head>
				<title>whoami?</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.png" />
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link
					rel="preconnect"
					href="https://fonts.gstatic.com"
					crossOrigin="true"
				/>
				<link
					href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500&family=Raleway:wght@400;500&display=swap"
					rel="stylesheet"
				/>
			</Head>
			<AppShell
				styles={{
					main: {
						background: "#d2e4ff",
						paddingLeft: "0px",
						paddingRight: "0px",
						paddingBottom: "60px",
					},
				}}
				fixed
				footer={
					<Footer height={60} p="md">
						<MyFooter />
					</Footer>
				}
				header={
					<Header height={70} background={"#d2e4ff"}>
						<div className="flex justify-center py-4">
							<div className="justify-between flex w-10/12 lg:w-10/12 items-end">
								<Link href="/">
									<div className="font-raleway text-2xl cursor-pointer font-semibold">
										Matthew Kim
									</div>
								</Link>

								<Link href="/projects">
									<div className="font-raleway text-xl font-semibold cursor-pointer">
										Projects
									</div>
								</Link>
							</div>
						</div>
					</Header>
				}
			>
				{children}
			</AppShell>
		</div>
	);
};
