import { AppShell, Footer, Group, Header, Text } from "@mantine/core";
import MyFooter from "./MyFooter";
import Head from "next/head";
import Link from "next/link";

export const ApplicationContainer = ({ children }) => {
	return (
		<div>
			<Head>
				<title>whoami?</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.png" />
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link
					rel="preconnect"
					href="https://fonts.gstatic.com"
					crossOrigin="true"
				/>
				<link
					href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500&family=Raleway:wght@400;500&display=swap"
					rel="stylesheet"
				/>
			</Head>
			<AppShell
				styles={{
					main: {
						background: "#FFFFFF",
						width: "100vw",
						height: "100vh",
						paddingLeft: "0px",
					},
				}}
				fixed
				footer={
					<Footer height={60} p="md">
						<MyFooter />
					</Footer>
				}
				header={
					<Header height={70}>
						<div className="flex justify-center py-4">
							<div className="justify-between flex w-11/12 md:w-6/12 items-end">
								<Link href="/">
									<div className="font-raleway text-2xl cursor-pointer font-semibold">
										Matthew Kim
									</div>
								</Link>
								<div className="font-raleway font-semibold text-xl">
									<Link href="/projects">
										<div className="cursor-pointer">Projects</div>
									</Link>
								</div>
							</div>
						</div>
					</Header>
				}
			>
				{children}
			</AppShell>
		</div>
	);
};
