import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { ApplicationContainer } from "../components/ApplicationContainer";
import Hero from "../components/Hero";

const technologiesDb = [
	{
		name: "Programming Languages",
		things: [
			{
				thing: "Java",
			},
			{
				thing: "Python",
			},
			{
				thing: "Javascript",
			},
		],
	},
	{
		name: "Frameworks",
		things: [
			{
				thing: "Next.js",
			},
			{
				thing: "React.js",
			},
			{
				thing: "React Native",
			},
			{
				thing: "Node.js",
			},
			{
				thing: "Serverless Framework",
			},
			{
				thing: "Express.js",
			},
		],
	},
	{
		name: "Databases",
		things: [
			{
				thing: "MongoDB",
			},
			{
				thing: "DynamoDB",
			},
		],
	},
	{
		name: "Cloud",
		things: [
			{
				thing: "AWS",
			},
		],
	},
];

export default function Home() {
	const handleResume = () => {
		// using Java Script method to get PDF file
		fetch("resume.pdf").then((response) => {
			response.blob().then((blob) => {
				// Creating new object of PDF file
				const fileURL = window.URL.createObjectURL(blob);
				// Setting various property values
				let alink = document.createElement("a");
				alink.href = fileURL;
				alink.download = "Matthew Kim Resume 22.pdf";
				alink.click();
			});
		});
	};

	return (
		<div className="text-[#123693] tracking-tighter font-medium">
			<Head>
				<title>whoami?</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.png" />
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link
					rel="preconnect"
					href="https://fonts.gstatic.com"
					crossOrigin="true"
				/>
				<link
					href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@300;400;500&family=Raleway:wght@400;500&display=swap"
					rel="stylesheet"
				/>
			</Head>

			<section className="flex justify-center py-16">
				<section className="w-7/12 text-3xl font-opensans">
					<div>
						I&apos;m a software engineer that uses cloud services to build
						scalable, cost-effective, and efficient applications.{"   "}
					</div>
					<span className="mt-6 flex space-x-32 items-center text-xl font-normal">
						<a onClick={handleResume}>
							<div className="group flex space-x-4 items-center">
								<span className="group-hover:underline cursor-pointer">
									See Resume
								</span>
								<a className="cursor-pointer group-hover:ring-4 bg-[#ffdb13] group-hover:bg-[#0053d6] transition ease-in duration-200 h-12 w-12 flex justify-center items-center  rounded-full">
									<svg
										xmlns="http://www.w3.org/2000/svg"
										fill="none"
										viewBox="0 0 24 24"
										strokeWidth="1.5"
										stroke="currentColor"
										className="w-6 h-6 group-hover:text-white duration-100 ease-in transition "
									>
										<path
											strokeLinecap="round"
											strokeLinejoin="round"
											d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m0 12.75h7.5m-7.5 3H12M10.5 2.25H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z"
										/>
									</svg>
								</a>
							</div>
						</a>
						<Link href="/projects">
							<div className="group flex space-x-4 items-center">
								<span className="group-hover:underline cursor-pointer">
									See Projects
								</span>
								<a className="cursor-pointer group-hover:ring-4 bg-[#ffdb13] group-hover:bg-[#0053d6] transition ease-in duration-200 h-12 w-12 flex justify-center items-center  rounded-full">
									<svg
										xmlns="http://www.w3.org/2000/svg"
										fill="none"
										viewBox="0 0 24 24"
										stroke-width="1.5"
										stroke="currentColor"
										className="w-6 h-6 group-hover:text-white duration-100 ease-in transition "
									>
										<path
											stroke-linecap="round"
											stroke-linejoin="round"
											d="M12 18v-5.25m0 0a6.01 6.01 0 001.5-.189m-1.5.189a6.01 6.01 0 01-1.5-.189m3.75 7.478a12.06 12.06 0 01-4.5 0m3.75 2.383a14.406 14.406 0 01-3 0M14.25 18v-.192c0-.983.658-1.823 1.508-2.316a7.5 7.5 0 10-7.517 0c.85.493 1.509 1.333 1.509 2.316V18"
										/>
									</svg>
								</a>
							</div>
						</Link>
					</span>
					<div className="my-8 text-xl">
						<div className="font-normal">Skills</div>
						<div className="grid grid-cols-1 md:grid-cols-2 md:gap-x-20  lg:grid-cols-4 gap-y-4 lg:gap-0 text-lg">
							{technologiesDb.map(({ name, things }) => {
								return (
									<div className="my-1 ">
										<div className="text-base mb-1">{name}</div>
										<ul className="font-normal">
											{things.map(({ thing }) => {
												return <li className="text-base">{thing}</li>;
											})}
										</ul>
									</div>
								);
							})}
						</div>
					</div>
				</section>
			</section>

			<section className="py-20 flex justify-center bg-[#ffeacc] ">
				<section className="w-7/12 text-2xl font-opensans font-normal">
					<div className="grid grid-cols-1 lg:gap-x-12 lg:grid-cols-2">
						<div className="flex flex-col justify-between h-[500px]">
							<div>
								I&apos;m currently building a crop and soil analytics platform
								from data transmitted by our smart device using AWS.
							</div>

							<div className="text-lg">
								<div className="pb-12">
									<div className="pb-1">Our Soil Measurements</div>
									<ul>
										<li>• Nitrogen, Phosphorous, Potassium (NPK)</li>
										<li>• Temperature</li>
										<li>• Moisture</li>
										<li>• Acidity</li>
									</ul>
								</div>
								<a className="">
									<div className="group flex space-x-4 items-center">
										<span className="group-hover:underline cursor-pointer">
											Learn More
										</span>
										<a className="cursor-pointer group-hover:ring-4 bg-[#ffdb13] group-hover:bg-[#0053d6] transition ease-in duration-200 h-12 w-12 flex justify-center items-center  rounded-full">
											<svg
												xmlns="http://www.w3.org/2000/svg"
												fill="none"
												viewBox="0 0 24 24"
												stroke-width="1.5"
												stroke="currentColor"
												className="w-6 h-6 group-hover:text-white duration-100 ease-in transition "
											>
												<path
													stroke-linecap="round"
													stroke-linejoin="round"
													d="M15.59 14.37a6 6 0 01-5.84 7.38v-4.8m5.84-2.58a14.98 14.98 0 006.16-12.12A14.98 14.98 0 009.631 8.41m5.96 5.96a14.926 14.926 0 01-5.841 2.58m-.119-8.54a6 6 0 00-7.381 5.84h4.8m2.581-5.84a14.927 14.927 0 00-2.58 5.84m2.699 2.7c-.103.021-.207.041-.311.06a15.09 15.09 0 01-2.448-2.448 14.9 14.9 0 01.06-.312m-2.24 2.39a4.493 4.493 0 00-1.757 4.306 4.493 4.493 0 004.306-1.758M16.5 9a1.5 1.5 0 11-3 0 1.5 1.5 0 013 0z"
												/>
											</svg>
										</a>
									</div>
								</a>
							</div>
						</div>

						<div className=" bg-[#ffe6f0] h-full"></div>
					</div>
				</section>
			</section>
		</div>
	);
}
