import Head from "next/head";

const projectDb = [
	{
		name: "The Watermark",
		img: "",
		date: "August 2022",
		desc: "A website to advertise a luxury condo in Honolulu, Hawaii. The purpose of this website was to connect interested tenants to the realtor. Website uses Email.js to send forms to realtor's email.",
		demo: "",
		code: "https://github.com/friendlymatthew/watermark",
		technologies: "Next.js, React.js, Tailwindcss",
	},
	{
		name: "Facebook Campaign Spending Interface",
		img: "/fbinterface.png",
		date: "March 2022 - May 2022",
		desc: "A data vizualization application that uses Facebook Ad data to track campaign spending for the US 2020 Presidential election. I worked with the Wesleyan Media Project to provide week-by-week insights. The website needed to be modular as data was constantly being updated.",
		demo: "https://presidentwmp.vercel.app/",
		code: "https://github.com/friendlymatthew/facebookad",
		technologies: "Next.js, React.js, TailwindCSS",
	},
	{
		name: "SeekWMP - API",
		img: "/seekapi.png",
		date: "March 2022",
		desc: "A cloud-computed service that stores training data for ML model. The service is high performing and scalable. ",
		demo: "",
		code: "https://github.com/friendlymatthew/wmpseekapi",
		technologies:
			"Serverless Framework and AWS: DynamoDB, Lambda, API Gateway, CloudWatch, and CloudFormation",
	},
	{
		name: "SeekWMP",
		img: "/seek.png",
		date: "Oct 2021 - Feb 2022",
		desc: "An internal web tool to help research members to efficiently mark the region of interest within news clips. The purpose of this web tool was to expedite the workflow and create an efficient data pipeline to crowdsource training data.",
		demo: "https://seekwmp.vercel.app/?market=Portland&station=WPFO&title=DailyMailTV&snippet=be+taking+to+make+the+risks+are+worth+their+rewards+medical+staff+housekeeping+and+that+of+se+--+jesse:+jay+jacobs+the+ceo+of+the+timberlake+family+of+camps+is+talking+about+what+it+takes+to+operate+a+summer+camp+in+the+time+of+covid-19+before+the+recently+announced+new+york+ban+jacobs+had+planned+to+open+some+of+his&coder=eraab&url=covid/xWPFO_20200619_1100PM.mp4&id=4&seek=1357",
		code: "https://github.com/friendlymatthew/seekwmp",
		technologies: "Next.js, React.js, ReactPlayer, TailwindCSS, Qualtrics",
	},
	{
		name: "YOBO (You Only airBend Once)",
		img: "/yobo.png",
		date: "May 2021",
		desc: "A custom YOLOv3 network that detects Aang's face from Avatar: The Last Airbender. My friend and I collected training data from Season 1. We used an 80/20 split on our training data. The model was successful detecting Aang's face.",
		demo: "https://www.youtube.com/watch?v=IXJ6LRCrv8Q&feature=youtu.be",
		code: "https://github.com/matthewkmkim/YOBO",
		technologies: "Python",
	},
];

export default function projects() {
	return (
		<div className="flex justify-center pb-20">
			<Head>
				<title>projects</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="w-6/12">
				<div className="text-center text-2xl font-semibold">My Projects</div>

				<div className="grid grid-cols-1 divide-y-2">
					{projectDb.map(
						({ name, img, date, desc, demo, code, technologies }) => {
							return (
								<div className="py-8">
									<div className="text-md text-gray-600 pb-2">{date}</div>

									<div className="grid grid-cols-1 lg:grid-cols-2 order-1 gap-x-0 lg:gap-x-12">
										<img
											src={img}
											className=" border-black order-first lg:order-last  mb-4"
										></img>
										<div className="col-span-1 flex flex-col justify-between space-y-6">
											<div>
												<div className="text-2xl font-semibold">{name}</div>

												<div className="tracking-tight text-lg"> {desc}</div>
											</div>

											<div className="flex justify-start space-x-2">
												<a
													className="hover:text-white cursor-pointer items-center flex space-x-4 border-black border-2 py-1 px-3 rounded-md hover:bg-black transition ease-in duration-200"
													href={demo}
													target="_blank"
													rel="no_referrer"
												>
													<svg
														xmlns="http://www.w3.org/2000/svg"
														fill="none"
														viewBox="0 0 24 24"
														stroke-width="1.5"
														stroke="currentColor"
														className="w-5 h-5"
													>
														<path
															stroke-linecap="round"
															stroke-linejoin="round"
															d="M9 17.25v1.007a3 3 0 01-.879 2.122L7.5 21h9l-.621-.621A3 3 0 0115 18.257V17.25m6-12V15a2.25 2.25 0 01-2.25 2.25H5.25A2.25 2.25 0 013 15V5.25m18 0A2.25 2.25 0 0018.75 3H5.25A2.25 2.25 0 003 5.25m18 0V12a2.25 2.25 0 01-2.25 2.25H5.25A2.25 2.25 0 013 12V5.25"
														/>
													</svg>
													<div>Demo</div>
												</a>

												<a
													className="hover:text-white cursor-pointer items-center flex space-x-4 border-black border-2 py-1 px-3 rounded-md hover:bg-black transition ease-in duration-200"
													href={code}
													target="_blank"
													rel="no_referrer"
												>
													<svg
														xmlns="http://www.w3.org/2000/svg"
														fill="none"
														viewBox="0 0 24 24"
														stroke-width="1.5"
														stroke="currentColor"
														class="w-5 h-5"
													>
														<path
															stroke-linecap="round"
															stroke-linejoin="round"
															d="M14.25 9.75L16.5 12l-2.25 2.25m-4.5 0L7.5 12l2.25-2.25M6 20.25h12A2.25 2.25 0 0020.25 18V6A2.25 2.25 0 0018 3.75H6A2.25 2.25 0 003.75 6v12A2.25 2.25 0 006 20.25z"
														/>
													</svg>
													<div>Code</div>
												</a>
											</div>
										</div>
									</div>
								</div>
							);
						}
					)}
				</div>
			</div>
		</div>
	);
}
