import Head from "next/head";
import MyFooter from "../components/MyFooter";
import MyHeader from "../components/MyHeader";

const projectDb = [
	/*
	{
		name: "Plant Based Data",
		img: "/sensor.png",
		date: "July 2022 - Now",
		desc: "A web application and cloud service that collects soil data from IOT device using AWS IOT core. Web applicaton delivers visualization of current soil conditions across multiple farm plots.",
		demo: "",
		code: "https://github.com/friendlymatthew/",
		technologies:
			"Next.js, React.js, D3.js, Node.js, AWS: IOT Core, Lambda, DynamoDB, API Gateway, Cloudwatch",
	},
	{
		name: "The Watermark",
		img: "",
		date: "August 2022",
		desc: "A website to advertise a condo in Honolulu, Hawaii. The purpose of this website was to connect interested tenants to the realtor. Website uses Email.js to send forms to realtor's inbox.",
		demo: "",
		code: "https://github.com/friendlymatthew/watermark",
		technologies: "Next.js, React.js, Tailwindcss",
	},
	*/

	{
		name: "Facebook Campaign Spending Interface",
		img: "/presidents.png",
		date: "March 2022 - May 2022",
		desc: "A web application that compares campaigns’ spendings  on Facebook ads in each state during the 2020 US presidential election. This interactive timeline used data over 33-week period. I analyzed spending data, tabled results, and imaged spending data through custom chloropleth maps. This website was visited by journalists covering 2020 US election. ",
		demo: "https://presidentwmp.vercel.app/",
		code: "https://github.com/friendlymatthew/facebookad",
		technologies: "Next.js, React.js, TailwindCSS",
	},
	{
		name: "Seek",
		img: "/seek.png",
		date: "Oct 2021 - Feb 2022",
		desc: "A training data annotation platform that delegates 200+ tasks to 18 team members every semester and produces annotated video and audio data; ready to be consumed by ML models.",
		demo: "https://seekwmp.vercel.app/?market=Portland&station=WPFO&title=DailyMailTV&snippet=be+taking+to+make+the+risks+are+worth+their+rewards+medical+staff+housekeeping+and+that+of+se+--+jesse:+jay+jacobs+the+ceo+of+the+timberlake+family+of+camps+is+talking+about+what+it+takes+to+operate+a+summer+camp+in+the+time+of+covid-19+before+the+recently+announced+new+york+ban+jacobs+had+planned+to+open+some+of+his&coder=eraab&url=covid/xWPFO_20200619_1100PM.mp4&id=4&seek=1357",
		code: "https://github.com/friendlymatthew/seekwmp",
		technologies: "Next.js, React.js, ReactPlayer, TailwindCSS, Qualtrics",
	},
	{
		name: "Seek - API",
		img: "/seekapi.png",
		date: "March 2022",
		desc: "A backend service written in Serverless and Node.js that stores ML training data in DynamoDB using API Gateway and AWS Lambda.",
		demo: "",
		code: "https://github.com/friendlymatthew/wmpseekapi",
		technologies:
			"Serverless Framework and AWS: DynamoDB, Lambda, API Gateway, CloudWatch, and CloudFormation",
	},
	{
		name: "Hungry Cloud",
		img: "/hungry.png",
		date: "March 2022",
		desc: "Try to feed the cloud as many rice grains within 15 seconds by mashing your keyboard. Hungry Cloud is a serverless API that feeds rice grains to DynamoDB. DynamoDB is a fast and flexible non-relational database service for applications that need consistent, single-digit millisecond latency at any scale.",
		demo: "http://hungrycloud.vercel.app",
		code: "https://github.com/friendlymatthew/hungrycloud",
		subtext:
			"Deleted database due to billing. I couldn't afford the hosting fees and I quickly became hungry.",
		technologies: "Next.js, React.js, Node.js, Serverless Framework, DynamoDB",
	},
	{
		name: "YOBO (You Only airBend Once)",
		img: "/yobo.png",
		date: "May 2021",
		desc: "Built model that identifies Aang from Avatar: The Last Airbender using YOLOv3, a real-time object detection system.",
		demo: "https://www.youtube.com/watch?v=IXJ6LRCrv8Q&feature=youtu.be",
		code: "https://github.com/matthewkmkim/YOBO",
		technologies: "Python",
	},
];

export default function projects() {
	return (
		<div className="bg-[#d2e4ff] text-[#123693]">
			<Head>
				<title>projects | matthew kim</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.png" />
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link
					rel="preconnect"
					href="https://fonts.gstatic.com"
					crossOrigin="true"
				/>
				<link
					href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@300;400;500&family=Raleway:wght@400;500&display=swap"
					rel="stylesheet"
				/>
			</Head>

			<header className="bg-[#f0ebff]">
				<MyHeader color={"#e6d6ff"} tome={true} />
			</header>

			<main className="flex-1 overflow-y-auto bg-[#f0ebff]">
				<div className="flex justify-center">
					<div className="w-10/12 xl:w-6/12">
						<div className="grid grid-cols-1 gap-y-12 first:my-10  divide-[#123693]">
							{projectDb.map(
								({
									name,
									img,
									date,
									desc,
									demo,
									code,
									technologies,
									subtext,
								}) => {
									return (
										<div
											key={name}
											className="p-8 border bg-white border-[#123693]"
										>
											<div className="text-md text-gray-600 pb-2 font-opensans tracking-tighter">
												{date}
											</div>

											<div className="grid grid-cols-1 lg:grid-cols-2 order-1 gap-x-0 lg:gap-x-12">
												<img
													src={img}
													className=" border-black order-first lg:order-last  mb-4"
												></img>

												<div className="col-span-1 flex flex-col justify-between space-y-6">
													<div>
														<div className="pb-1 text-2xl font-semibold font-raleway">
															{name}
														</div>

														<div className="tracking-tighter text-lg font-opensans">
															{" "}
															{desc}
															{subtext ? (
																<div className="my-4">{subtext}</div>
															) : (
																<></>
															)}
														</div>
													</div>
													<div className=" flex space-x-3 items-center">
														<svg
															xmlns="http://www.w3.org/2000/svg"
															viewBox="0 0 20 20"
															fill="currentColor"
															className="w-5 h-5"
														>
															<path
																fillRule="evenodd"
																d="M10 2.5c-1.31 0-2.526.386-3.546 1.051a.75.75 0 01-.82-1.256A8 8 0 0118 9a22.47 22.47 0 01-1.228 7.351.75.75 0 11-1.417-.49A20.97 20.97 0 0016.5 9 6.5 6.5 0 0010 2.5zM4.333 4.416a.75.75 0 01.218 1.038A6.466 6.466 0 003.5 9a7.966 7.966 0 01-1.293 4.362.75.75 0 01-1.257-.819A6.466 6.466 0 002 9c0-1.61.476-3.11 1.295-4.365a.75.75 0 011.038-.219zM10 6.12a3 3 0 00-3.001 3.041 11.455 11.455 0 01-2.697 7.24.75.75 0 01-1.148-.965A9.957 9.957 0 005.5 9c0-.028.002-.055.004-.082a4.5 4.5 0 018.996.084V9.15l-.005.297a.75.75 0 11-1.5-.034c.003-.11.004-.219.005-.328a3 3 0 00-3-2.965zm0 2.13a.75.75 0 01.75.75c0 3.51-1.187 6.745-3.181 9.323a.75.75 0 11-1.186-.918A13.687 13.687 0 009.25 9a.75.75 0 01.75-.75zm3.529 3.698a.75.75 0 01.584.885 18.883 18.883 0 01-2.257 5.84.75.75 0 11-1.29-.764 17.386 17.386 0 002.078-5.377.75.75 0 01.885-.584z"
																clipRule="evenodd"
															/>
														</svg>
														<div className="font-opensans tracking-tighter text-sm w-9/12">
															{technologies}
														</div>
													</div>

													<div className="flex justify-start space-x-2">
														{demo ? (
															<a
																className="font-raleway font-semibold cursor-pointer items-center flex space-x-4 border-[#123693] border py-1 px-3 rounded-md bg-[#f0ebff] hover:bg-white transition ease-in duration-200"
																href={demo}
																target="_blank"
																rel="noreferrer"
															>
																<svg
																	xmlns="http://www.w3.org/2000/svg"
																	fill="none"
																	viewBox="0 0 24 24"
																	strokeWidth="1.5"
																	stroke="currentColor"
																	className="w-5 h-5"
																>
																	<path
																		strokeLinecap="round"
																		strokeLinejoin="round"
																		d="M9 17.25v1.007a3 3 0 01-.879 2.122L7.5 21h9l-.621-.621A3 3 0 0115 18.257V17.25m6-12V15a2.25 2.25 0 01-2.25 2.25H5.25A2.25 2.25 0 013 15V5.25m18 0A2.25 2.25 0 0018.75 3H5.25A2.25 2.25 0 003 5.25m18 0V12a2.25 2.25 0 01-2.25 2.25H5.25A2.25 2.25 0 013 12V5.25"
																	/>
																</svg>
																<div>Demo</div>
															</a>
														) : (
															<></>
														)}

														<a
															className="font-raleway  font-semibold  cursor-pointer items-center flex space-x-4 border-[#123693] border py-1 px-3 rounded-md bg-[#f0ebff] hover:bg-white transition ease-in duration-200"
															href={code}
															target="_blank"
															rel="noreferrer"
														>
															<svg
																xmlns="http://www.w3.org/2000/svg"
																fill="none"
																viewBox="0 0 24 24"
																strokeWidth="1.5"
																stroke="currentColor"
																className="w-5 h-5"
															>
																<path
																	strokeLinecap="round"
																	strokeLinejoin="round"
																	d="M14.25 9.75L16.5 12l-2.25 2.25m-4.5 0L7.5 12l2.25-2.25M6 20.25h12A2.25 2.25 0 0020.25 18V6A2.25 2.25 0 0018 3.75H6A2.25 2.25 0 003.75 6v12A2.25 2.25 0 006 20.25z"
																/>
															</svg>
															<div>Code</div>
														</a>
													</div>
												</div>
											</div>
										</div>
									);
								}
							)}
						</div>
					</div>
				</div>
			</main>
			<footer className="bg-[#f0ebff]">
				<MyFooter />
			</footer>
		</div>
	);
}
